### ISSUE TITLE
Error during resolution of library with non-standard version

### ISSUE THREAD

**Issue by andrewconner** [alexarchambault/coursier#109]
I depend on `"org.feijoas" %% "mango" % "0.12"` in SBT, which causes this error during resolution:

```
java.lang.Exception: Exception during resolution
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$13.apply(Tasks.scala:282)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$13.apply(Tasks.scala:282)
	at scalaz.$bslash$div.leftMap(Either.scala:97)
	at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:282)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$15.apply(Tasks.scala:431)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$15.apply(Tasks.scala:431)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:429)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:120)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: assertion failed: URL: Users/andrew/.sbt/0.13/plugins/target/resolution-cache/com.google.code.findbugs/jsr305/[1.3,)/resolved.xml.xml, file: Users/andrew/.sbt/0.13/plugins/target/resolution-cache/com.google.code.findbugs/jsr305/%5B1.3,)/resolved.xml.xml
	at scala.Predef$.assert(Predef.scala:179)
	at coursier.Cache$$anonfun$11.apply(Cache.scala:306)
	at coursier.Cache$$anonfun$11.apply(Cache.scala:299)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721)
	at coursier.Cache$.download(Cache.scala:299)
	at coursier.Cache$.file(Cache.scala:410)
	at coursier.Cache$$anonfun$fetch$1.apply(Cache.scala:456)
	at coursier.Cache$$anonfun$fetch$1.apply(Cache.scala:455)
	at coursier.ivy.IvyRepository$$anonfun$find$2.apply(IvyRepository.scala:261)
	at coursier.ivy.IvyRepository$$anonfun$find$2.apply(IvyRepository.scala:260)
```

It appears to be related to mango's dependency on Google's findbugs, with a version of `[1.3,)`. See: http://mvnrepository.com/artifact/org.feijoas/mango_2.11/0.12. Since maven allows it, the file path may need to be escaped.

**Comment by alexarchambault** [comment]
This is the same kind of issue as the second point of https://github.com/alexarchambault/coursier/issues/104. This is fixed in master, and should be in the upcoming `1.0.0-M4` milestone (should be later today or tomorrow).

**Comment by andrewconner** [comment]
Ah, thanks @alexarchambault. Sorry for wasting your time :+1:

**Comment by alexarchambault** [comment]
@andrewconner you're welcome! (nothing to be sorry about... :-)
