### ISSUE TITLE
Not so helpful errors

### ISSUE THREAD

**Issue by crispywalrus** [alexarchambault/coursier#123]
Admittedly I'm using sbt-pom-reader so I can understand it failing but I don't see how to debug this at the pom level. Any clue?

````
> last adserver-replay/*:update
java.lang.Exception: Encountered 1 error(s) in dependency resolution
	at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:307)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$15.apply(Tasks.scala:416)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$15.apply(Tasks.scala:416)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:414)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:121)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (adserver-replay/*:update) java.lang.Exception: Encountered 1 error(s) in dependency resolution
````

**Comment by alexarchambault** [comment]
Indeed, this particular message is not particularly helpful! :-|

A slightly more better one should have been printed above though, in the command that printed the error. Something like
```
1 error(s):
  org:not-found_2.11:1.0:
    /home/user/.sbt/0.13/plugins/target/resolution-cache/org/not-found_2.11/1.0/resolved.xml.xml: not found
    Not found
    /home/user/.ivy2/local/org/not-found_2.11/1.0/ivys/ivy.xml: not found
    Download error: Caught java.io.FileNotFoundException: https://repo.jfrog.org/artifactory/libs-release-bintray/org/not-found_2.11/1.0/not-found_2.11-1.0.pom?referrer (https://repo.jfrog.org/artifactory/libs-release-bintray/org/not-found_2.11/1.0/not-found_2.11-1.0.pom?referrer)
    Download error: Caught java.io.FileNotFoundException: https://repo1.maven.org/maven2/org/not-found_2.11/1.0/not-found_2.11-1.0.pom (https://repo1.maven.org/maven2/org/not-found_2.11/1.0/not-found_2.11-1.0.pom)
```

Having better / clearer error messages is something I'd like to have before `1.0.0`, this is tracked by https://github.com/alexarchambault/coursier/issues/111.

**Comment by alexarchambault** [comment]
1.0.0-M13 shoud print better errors. Closing this.
