### ISSUE TITLE
launch incurs NoSuchMethodError while fetch succeeds

### ISSUE THREAD

**Issue by paulp** [alexarchambault/coursier#141]
With the same ammonite version, fetch and launch land at different places. They enumerate identical dependencies, but in the fetch version ammonite's banner is "Welcome to the Ammonite Repl 0.5.4" whereas in the failing version it's 0.5.0. The same behavior persists after removing ~/.coursier so if it's a caching issue from an earlier run with version 0.5.0 I don't know where.

```
% java -cp "$(coursier fetch -p com.lihaoyi:ammonite-repl_2.11.7:0.5.4)" ammonite.repl.Main
...
Welcome to the Ammonite Repl 0.5.4
(Scala 2.11.7 Java 1.8.0_72)
@
```

```
% coursier launch com.lihaoyi:ammonite-repl_2.11.7:0.5.4
...
Welcome to the Ammonite Repl 0.5.0
(Scala 2.11.7 Java 1.8.0_72)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at coursier.Bootstrap.main(Bootstrap.java:365)
Caused by: java.lang.NoSuchMethodError: ammonite.terminal.TermCore$.ansiRegex()Lscala/util/matching/Regex;
	at ammonite.terminal.Prompt.<init>(TermCore.scala:331)
	at ammonite.terminal.Prompt$.apply(TermCore.scala:299)
```

**Comment by alexarchambault** [comment]
That's a regression, I changed things related to that recently... Looking at it.
