### ISSUE TITLE
Support repositories hosted with plugins like fm-sbt-s3-resolver

### ISSUE THREAD

**Issue by mdedetrich** [alexarchambault/coursier#164]
At work, we currently use https://github.com/frugalmechanic/fm-sbt-s3-resolver as a way to store our private artifacts in an S3 repo. This doesn't work with coursier (fm-sbt-s3-resolver hooks onto ivy style URL resolution which I think is ignored by coursier)

I am not sure how hard it is for coursier to pick up plugins like this, if it can't, would adding native support to coursier be a solution? I think ideally it would be good (if possible) to transparently support such plugins, as each plugin has their own repository format and it would mean less work

I also have a stack trace, but since it has some private info I don't want to put it out publicly (I can email it if needed)

**Comment by alexarchambault** [comment]
It should be possible to support other protocol directly via `java.net.URL`. So support S3 via the handlers of fm-sbt-s3-resolver.

`java.net.URL` is currently used for HTTP, but it is assumed that the underlying protocol is HTTP, as the resulting connection is cast as a `HTTPURLConnection`. But some more generic code could be written for other protocols. Then fm-sbt-s3-resolver would work directly from the SBT plugin.

**Comment by alexarchambault** [comment]
@mdedetrich Is it something you'd like to take a cut at?

The `java.net.URL` based code in coursier is actually already quite generic, and should be able to handle other protocols, via the `java.net.URLStreamHandler` mechanism.

So to have something that works from the SBT plugin, it should only be a matter of having a first SBT plugin that registers a `java.net.URLStreamHandler` for the `s3://` URLs (this plugin can be independent of coursier). Then a few minor things would have to be addressed in the `cache` module, so that it doesn't reject protocols other than `file` / `http` / `https` (I can take care of that), and that should be it.

**Comment by mdedetrich** [comment]
Ill have a look into it in the weekend, ideally I would wan't this to be part of coursier as it means it will create less friction

**Comment by rtfpessoa** [comment]
@alexarchambault Any news about this?

**Comment by mdedetrich** [comment]
@rtfpessoa I had a look at the code for coursier and its not really possible to make `fm-sbt-s3-resolver` work with coursier, you would have to make a specific plugin for coursier (coursier has no concept of ivy resolvers, it does all of that handling itself)

I believe @alexarchambault was in the process of documenting how coursier plugins would work and/or improving the plugin functionality. When that is done I will probably look into implementing a version of `fm-sbt-s3-resolver` for coursier specifically

**Comment by rtfpessoa** [comment]
@mdedetrich I am currently using, https://github.com/ohnosequences/sbt-s3-resolver, 
I suspect it might be the same problem.

**Comment by mdedetrich** [comment]
I would also suspect that its the same problem, unless `sbt-s3-resolver` is doing something out of the ordinary

**Comment by alexarchambault** [comment]
I was about to write a few words about custom protocols:

The support for i is in place, and is illutstrated a bit in the tests, [here](https://github.com/alexarchambault/coursier/blob/3ffba8b97470f35d1df88d0607a3b0ae1a76fe76/tests/jvm/src/test/scala/coursier/cache/protocol/TestprotocolHandler.scala).

To handle a custom protocol `custom`, you need to put a class extending `java.net.URLStreamHandler` for it as `coursier.cache.protocol.CustomHandler` in the classpath (under this particular `coursier.cache.protocol` namespace, with class name: the - capitalized - protocol with `Handler` as suffix, so `CustomHandler`).

Then coursier will be able to handle repositories with a base like `custom://...`.

The custom `java.net.URLStreamHandler` would typically be put in a separate library, added in the SBT plugin classpath (a simple `libraryDependencies += ...` for it in `project/plugins.sbt` should be fine I think).

**Comment by alexarchambault** [comment]
So for S3, we would need a lib for that exposing `coursier.cache.protocol.S3Handler`. I guess things like [s3rver](https://www.npmjs.com/package/s3rver) would then allow to test that on the CI.

**Comment by rtfpessoa** [comment]
@alexarchambault what would be the best way to feed the connection with the credentials?

Environmental variables?

**Comment by rtfpessoa** [comment]
Just did a fast implementation: https://gist.github.com/rtfpessoa/407dcc6376027d8567c96b0128b76487

Will do some testing.

**Comment by alexarchambault** [comment]
For authentication, either the `URLStreeamHandler` handles it itself (which has some drawbacks, like the caches of the various users mixed together indifferently in the cache), or the `URLConnection`s it returns implement [`coursier.AuthenticatedURLConnection `](https://github.com/alexarchambault/coursier/blob/3ffba8b97470f35d1df88d0607a3b0ae1a76fe76/cache/src/main/scala/coursier/Cache.scala#L23-L25). In that case, authentication is handled like the HTTP one (that is via the `coursierCredentials` settings - just `credentials` with the forthcoming `1.0.0-M12-1` - from the SBT plugin, with URLs like `s3://key:secret@bucket/...` from the command line, ...).

The credentials handling could be enhanced to deal better with the AWS ones (and also with credentials written in a file too).

**Comment by alexarchambault** [comment]
I'd be fine with something workish as a PR, proper tests can be written later (before 1.0 final say).

**Comment by rtfpessoa** [comment]
To do some testing etc, I created this: https://github.com/rtfpessoa/coursier-s3

After that I tried with one small project.

With `sbt-s3-resolver` it does not seem to work. 

Then I tried `fm-sbt-s3-resolver` and I have the some weird issue.

In the logs I get:

```
java.lang.Exception: Exception during resolutioncy.com/org/dep_2.11/3.0.12/dep_2.11-3.0.12.pom.sha1
        at coursier.Tasks$$anonfun$resolutionTask$1$$anonfun$28.apply(Tasks.scala:462)
s3://s3-at coursier.Tasks$$anonfun$resolutionTask$1$$anonfun$28.apply(Tasks.scala:462)oundation_2.11-3.0.12.pom
        at scalaz.$bslash$div.leftMap(Either.scala:97)
        at coursier.Tasks$$anonfun$resolutionTask$1.coursier$Tasks$$anonfun$$resolution$1(Tasks.scala:462)
        at coursier.Tasks$$anonfun$resolutionTask$1$$anonfun$apply$35.apply(Tasks.scala:508)
        at coursier.Tasks$$anonfun$resolutionTask$1$$anonfun$apply$35.apply(Tasks.scala:508)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
        at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:501)
        at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:227)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
        at fm.sbt.s3.Handler.openConnection(Handler.scala:24)
        at java.net.URL.openConnection(URL.java:979)
        at coursier.Cache$.coursier$Cache$$urlConn$1(Cache.scala:317)
        at coursier.Cache$$anonfun$remote$1$1$$anonfun$apply$14$$anonfun$apply$15.apply(Cache.scala:451)
        at coursier.Cache$$anonfun$remote$1$1$$anonfun$apply$14$$anonfun$apply$15.apply(Cache.scala:446)
        at coursier.Cache$.coursier$Cache$$downloading(Cache.scala:195)
        at coursier.Cache$$anonfun$remote$1$1$$anonfun$apply$14.apply(Cache.scala:446)
        at coursier.Cache$$anonfun$remote$1$1$$anonfun$apply$14.apply(Cache.scala:446)
        at coursier.Cache$.coursier$Cache$$withLockFor(Cache.scala:164)
        at coursier.Cache$$anonfun$remote$1$1.apply(Cache.scala:445)
        at coursier.Cache$$anonfun$remote$1$1.apply(Cache.scala:445)
        at scalaz.concurrent.Task$.Try(Task.scala:386)
        at scalaz.concurrent.Task$$anonfun$apply$10.apply(Task.scala:286)
        at scalaz.concurrent.Task$$anonfun$apply$10.apply(Task.scala:286)
        at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380)
        at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:coursierResolution) java.lang.Exception: Exception during resolution
[error] Total time: 20 s, completed May 25, 2016 2:07:15 PM
```

Any ideas?

**Comment by rtfpessoa** [comment]
I think is coursier that is not getting my handler, the log I have is only from `fm-sbt-s3-resolver `.

**Comment by rtfpessoa** [comment]
I removed the last comment to summary the new findings here.

I created a repo for the plugin here: https://github.com/rtfpessoa/coursier-s3 

After that I tried using it with one small project, with one private s3 dependency.

With `sbt-s3-resolver` it does not seem to work. Maybe it needs other tweaks? Any ideas?

Then I tried `fm-sbt-s3-resolver` and I have the one weird issue.

Since `fm-sbt-s3-resolver` adds their [dummy s3 handler implementation](https://github.com/frugalmechanic/fm-sbt-s3-resolver/blob/master/src/main/scala/fm/sbt/s3/Handler.scala) to [the java factory](https://github.com/frugalmechanic/fm-sbt-s3-resolver/blob/master/src/main/scala/fm/sbt/S3ResolverPlugin.scala#L55) it seems to be the only handler added and when used somewhere crashes.

To continue with my tests I had to compile `fm-sbt-s3-resolver` locally and force my handler.

After this I was able to have the project compiling.

@alexarchambault  is coursier adding S3Handler to the URLStreamHandlerFactory?
If not maybe it should. Or Maybe this is a problem on the  `fm-sbt-s3-resolver` side.

Do you have any solution about this?

**Comment by alexarchambault** [comment]
fm-sbt-s3-resolver indeed registers its own URL handler, although if coursier finds one of its own, it should use it instead... Maybe you could try with a slightly different protocol (like `s3a`, with handler class `S3aHandler` for coursier), and see if it works.

**Comment by rtfpessoa** [comment]
I think that wont work because I cannot create `s3a` urls unless `coursier` binds one handler to the URLStreamHandlerFactory that know the protocol.

**Comment by rtfpessoa** [comment]
I was only able to make it work by adding this:
```scala
object S3URLStreamHandlerFactory extends URLStreamHandlerFactory {
    def createURLStreamHandler(protocol: String): URLStreamHandler = protocol match {
      case "s3a" => new coursier.cache.protocol.S3aHandler()
      case _ => null
    }
  }

  URL.setURLStreamHandlerFactory(S3URLStreamHandlerFactory)
```

to the build.sbt of the project using coursier.

**Comment by alexarchambault** [comment]
I think I'll create a separate branch with some s3rver based integration tests, to have a closer look at this problem.

**Comment by rtfpessoa** [comment]
I am doing some utils in my project to make this easy to use, and I am going to try this in more projects in my company.

**Comment by rtfpessoa** [comment]
Added some docs here: https://github.com/rtfpessoa/coursier-s3#s3-coursier-plugin

**Comment by rtfpessoa** [comment]
@alexarchambault, I have been testing it with other projects and I found two major problems.

* When it fails for network reasons or even for file not found, the error my plugin is giving is an ugly exception which gives a weird log, not like the other resolvers. What is the correct way for me to return an error?

* I seem to be having some problems with partial dependencies. I have one project with a dependency version like `DEV-4.0.76.+`, that with regular sbt finds the real dependency `DEV-4.0.76.22`. With coursier I am having some weird errors it seems to be looking for `[DEV-4.0.76,DEV-4.0.77-a1)`.

Any ideas?

**Comment by alexarchambault** [comment]
@rtfpessoa About the errors printed by the plugin, these definitely ought to be enhanced (https://github.com/alexarchambault/coursier/issues/123). They should be by 1.0 final.

About version intervals, they should be handled (e.g. `coursier fetch "com.chuusai:shapeless_2.11:[2.3,2.4)"` works, `coursier fetch "com.chuusai:shapeless_2.11:2.3.+"` does too). These only work for Maven repositories though (even though `x.y.+` is an Ivy syntax), and require the repository to expose versioning metadata (like https://repo1.maven.org/maven2/io/get-coursier/coursier_2.11/maven-metadata.xml).

**Comment by rtfpessoa** [comment]
It is an Ivy repository. How can we add support for this?

**Comment by alexarchambault** [comment]
That requires a few additions to coursier. As I see it for now, it's not straightforward. It would require:
- passing an extra - optional - parameter to the `find` method of `Repository` to list a directory elements,
- have `IvyRepository` use it to list available versions of a given module,
- write a method creating a value to pass as this parameter, from a list of repositories.
  - For HTTP, it could use [jsoup](https://jsoup.org/) to get a directory web page and extract links to sub-elements.
  - For other protocols, it could check if the `coursier.cache.protocol.*Handler` implements a new `coursier.ListElements` trait, with a method to list elements under a directory.

**Comment by alexarchambault** [comment]
Actually, there should be more straightforward ways (but possibly a bit more hackish) of doing that, without changing much of what's already there.

One could ask the `cache` module to support the following: when asked a URL with a path like `/a/b/.coursier-content` (or `/a/b/.coursier-content$`, ...), it should list the entries of directory `/a/b` (by any mean - jsoup for HTTP, more specific things for custom protocols), and do as if `/a/b/.coursier-content` actually existed, with content: the entry names separated by `\n`. This content could be kept in cache, and be updated if asked so like the metadata or JARs. Then `IvyRepository` could request the content of whatever directory it needs, and get available versions this way.

**Comment by rtfpessoa** [comment]
The first option seems better. But the second is definitely easier to implement.

Maybe I will get some time to try one of them, but I will be out for 1 week.

**Comment by alexarchambault** [comment]
I have an implementation of version intervals handling for Ivy repos. I'll clean it a bit and push it tomorrow I think.

**Comment by rtfpessoa** [comment]
Just checked your PR and I have some questions:

- Is there a summary of the architecture of `coursier`?
- What is the js / jvm core about?
- What is the `.directory`? Is it the fake file to list files in there? Where is it being used?
- Where could I look to add my implementation? Is the comment https://github.com/alexarchambault/coursier/issues/164#issuecomment-222312597 still a valid option after this changes?

Sorry for the basic questions but I am starting to get stuck when reading the code.

**Comment by alexarchambault** [comment]
I can understand that, a few parts of coursier grew a bit out of control since its inception, and I've not been too keen to refactor them not to break things before 1.0... I'll write a design document in the coming days.

The README succinctly says [a few words](https://github.com/alexarchambault/coursier#api-1) about the modules of coursier. Basically, `core` is a bunch of definitions (`Definitions.scala`, `Repository.scala`, ...), along with the quite central `Resolution`, the state of a resolution, having a bunch of method providing a few infos about it. `ResolutionProcess` uses these and a fetcher, providing content wrapped in a monad, to compute the next resolution state, wrapped in the same monad. Recursively, this can compute the final state of the resolution.

`core` targets both the JVM and scala-js, so it has a few platform dependent code under `core/jvm` and `core/js`, but most of its sources are under `core/shared`. It's a typical scala on JVM + scala-js cross-compiled source layout.

Then `cache` provides implementations of the previous fetcher methods, using a specific monad (currently, `scalaz.concurrent.Task`). Thus, when using it, we get the final state of the resolution wrapped in a `Task`.

**Comment by alexarchambault** [comment]
About `.directory` (addition of https://github.com/alexarchambault/coursier/issues/265), that's where the cache keeps the content of a URL whose path ends with `/` (that should designate a directory). E.g. `https://oss.sonatype.org/content/repositories/releases/io/get-coursier/sbt-coursier_2.10_0.13/` is such a URL. The web page ones gets when navigating to it is kept in cache under `~/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/releases/io/get-coursier/sbt-coursier_2.10_0.13/.directory`. This webpage is then used by `IvyRepository` (since https://github.com/alexarchambault/coursier/issues/265) to list the elements under this directory - by navigating the links on this page (Ivy does [similar things](https://github.com/sbt/ivy/blob/89704c7e6b3b5f97c41a6b4f16b43631ced88e6d/src/java/org/apache/ivy/util/url/ApacheURLLister.java)). That's what it does around [here](https://github.com/alexarchambault/coursier/blob/bde69ecb1097bb2e47ff47a09f17f566ce3fc98f/core/shared/src/main/scala/coursier/ivy/IvyRepository.scala#L146-L182), it builds a directory URL, fetches its content, and knows the elements of the directory via the links in the content.

That makes https://github.com/alexarchambault/coursier/issues/164#issuecomment-222312597 not relevant any more. To support version ranges for Ivy repo via S3, you should just have the `s3c://` URL handler return a webpage similar to the ones of [Sonatype](https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier_2.11/) or [bintray](http://dl.bintray.com/scalaz/releases/org/scalaz/stream/scalaz-stream_2.11/) if asked a directory `InputStream`. With relative links ending in `/` for directories in particular. `IvyRepository` will just parse this web page, and list the elements out of it.

**Comment by rtfpessoa** [comment]
@alexarchambault, after my vacations, I finally got time to get into this again.

https://github.com/rtfpessoa/coursier-s3/commit/6c69124689c737ababa61c5af30ae321ed7332bc#diff-9dcc466beb602cff871853eb020f5f54R37 creates some initial support for directories. Can you please take a look and give me some feedback?

I did some minor refactor to extract the s3 client stuff to its own class, forget about that part.

**Comment by alexarchambault** [comment]
@rtfpessoa I'll have a look at https://github.com/rtfpessoa/coursier-s3/pull/2 (that looks fine at first). You shouldn't get requests with versions like `[DEV-4.0.91,DEV-4.0.92-a1)` though... That may mean something's not right when `IvyRepository` tries to list the available versions.

**Comment by rtfpessoa** [comment]
@alexarchambault any news about this? Do you have any starting point for me to look at? Maybe I can help.

**Comment by alexarchambault** [comment]
@rtfpessoa @darkjh I just pushed https://github.com/alexarchambault/coursier/pull/289. There still are a lot of holes in it though. Feel free to comment the PR or ask questions about it anyway.

**Comment by rtfpessoa** [comment]
@alexarchambault after some checks in the current tests I only found tests for Ivy resolution for plugins, not libraries. Maybe that is the problem.

At least I think that is the case in `IvyTests.scala`.

How do I create a library test, the module example is:

```
val sbtRepo = IvyRepository(
    "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/" +
      "[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)" +
      "[revision]/[type]s/[artifact](-[classifier]).[ext]",
    dropInfoAttributes = true
)
val mod = Module(
  "com.github.ddispaltro", "sbt-reactjs", Map("sbtVersion" -> "0.13", "scalaVersion" -> "2.10")
)
val ver = "0.6.+"
```

Can you help?

**Comment by tpunder** [comment]
FYI https://github.com/frugalmechanic/fm-sbt-s3-resolver version 0.10.0 now implements an HttpURLConnection for the s3:// protocol and appears to work with Coursier 1.0.0-M15.

Here is the commit: https://github.com/frugalmechanic/fm-sbt-s3-resolver/commit/1aa10983e3ba70eefef014fbdd57fb6a66c0a47f

**Comment by earthmonkey0** [comment]
@tpunder I am currently using fm-sbt-s3-resolver 0.11.0 and attempting to use sbt-coursier 1.0.0-RC13. When I add coursier as a plugin It does not check any of the s3 resolvers when resolving resulting in many errors when building. Did you have to do anything else to get coursier to use the s3 resolvers?

**Comment by tpunder** [comment]
@earthmonkey0 Try upgrading to fm-sbt-s3-resolver 0.13.0 since there have been a handful of other improvements that were needed for SBT 1.0 support which is using the same code path.

```
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.13.0")
```

**Comment by earthmonkey0** [comment]
I am unable to upgrade to sbt 1.0 right now but did upgrade to fm-sbt-s3-resolver 0.13. I am still seeing the same error that it is not looking at the s3 resolvers, should I be including anything else?

plugins.sbt
```
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.13.0")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC13") 
```

relock error
```
...
[error] (models/*:coursierResolutions) coursier.ResolutionException: Encountered 6 error(s) in dependency resolution:
[error]     clientsharedmodels:clientsharedmodels_2.11:1.+:
[error]         not found:
[error]             /Users/David/.ivy2/local/sharedmodels/sharedmodels_2.11
[error]             https://repo1.maven.org/maven2/sharedmodels/sharedmodels_2.11/maven-metadata.xml
[error]             http://repo.typesafe.com/typesafe/releases/sharedmodels/sharedmodels_2.11/maven-metadata.xml
...
```

**Comment by fernando-oktana** [comment]
@earthmonkey0 did you try this solution?

https://github.com/frugalmechanic/fm-sbt-s3-resolver/issues/8
where did you plug s3 plugin?

- root/project/project/plugins.sbt
- root/project/plugins.sbt

**Comment by er1c** [comment]
FYI, I have a PR that updates the `sbt-coursier` plugin to work with [fm-sbt-s3-resolver](https://github.com/frugalmechanic/fm-sbt-s3-resolver).  The S3 resolver plugin was working fine, but the plumbing wasn't hooked up yet in the `sbt-coursier`: https://github.com/coursier/sbt-coursier/pull/49
