### ISSUE TITLE
Runs fine with "./coursier" but not with "java -jar coursier"

### ISSUE THREAD

**Issue by hedefalk** [alexarchambault/coursier#176]
I'm trying to add this for ensime-atom https://github.com/ensime/ensime-atom/issues/183

It works fine using ./coursier, but @fommil expressed the issue that this will not run with Windows so I tried with "java -jar coursier" and this gives:

```
~/d/p/a/ensime_update_coursier ❯❯❯ /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java -jar coursier fetch -m update-changing -r file:///$HOME/.m2/repository -r https://oss.sonatype.org/content/repositories/snapshots -r https://jcenter.bintray.com/ org.ensime:ensime_2.11:0.9.10-SNAPSHOT -V org.scala-lang:scala-compiler:2.11.7 -V org.scala-lang:scala-library:2.11.7 -V org.scala-lang:scala-reflect:2.11.7 -V org.scala-lang:scalap:2.11.7

  Dependencies:
org.ensime:ensime_2.1:0.9.10-SNAPSHOT:default(compile)
  Force versions:
org.scala-lang:scala-compiler:2.11.7
org.scala-lang:scala-library:2.11.7
org.scala-lang:scala-reflect:2.11.7
org.scala-lang:scalap:2.11.7
Exception in thread "main" java.lang.VerifyError: Inconsistent stackmap frames at branch target 235
Exception Details:
  Location:
    coursier/a/bf.c_(Ljava/lang/Object;)Ljava/lang/Object; @235: new
  Reason:
    Type uninitialized 150 (current frame, stack[1]) is not assignable to 'c/aw' (stack map, stack[1])
  Current Frame:
    bci: @215
    flags: { }
    locals: { top, 'c/C', 'c/b/d/bJ' }
    stack: { 'java/lang/Object', uninitialized 150, uninitialized 150, 'c/C', integer }
  Stackmap Frame:
    bci: @235
    flags: { }
    locals: { top, 'c/C' }
    stack: { 'java/lang/Object', 'c/aw', 'c/aw', 'c/C' }
  Bytecode:
    0x0000000: 2a2b c000 074d 4c2c 594d c601 6f2c b600
    0x0000010: 25c0 000e 4e2c b600 26c0 000a 4db2 001c
    0x0000020: 57b2 001b 572d b800 202b b400 1f2d b900
    0x0000030: 3602 004c b200 1a2b b600 3499 00b9 2c04
    0x0000040: 3e59 4cb6 0028 1d64 9a00 26bb 0007 59bb
    0x0000050: 0006 592c b600 29c0 0014 b600 31b7 0022
    0x0000060: bb00 1659 2cb7 0032 b700 24a7 007c 2cbb
    0x0000070: 0011 59b7 002e b200 1d59 4cb6 002a b600
    0x0000080: 27c0 0008 b900 3501 00c0 000a 4cb2 001e
    0x0000090: 572b b800 2d4c bb00 0759 2b2b 594c c100
    0x00000a0: 0699 002f 2bc0 0006 594c b600 23c0 0019
    0x00000b0: 4cbb 0016 592c bb00 1259 2bb7 002f b200
    0x00000c0: 1d59 4cb6 002a b600 27b7 0032 4ca7 0016
    0x00000d0: b200 1a2b b600 3499 0014 bb00 1759 2cb7
    0x00000e0: 0033 4c2b b700 244c a700 4bbb 000d 592b
    0x00000f0: b700 2cbf 2bc1 0006 9900 782b c000 0659
    0x0000100: 4cb6 0023 c000 194c bb00 0759 bb00 0659
    0x0000110: 2bb7 0022 bb00 1659 2cbb 0013 592b b700
    0x0000120: 30b2 001d 594c b600 2ab6 0027 b700 32b7
    0x0000130: 0024 4c2b 594c b600 25c0 0002 4d2b b600
    0x0000140: 26c0 0015 4cbb 0007 592c 2bb7 0024 594c
    0x0000150: 594c b600 25c0 0002 4d2b b600 26c0 0015
    0x0000160: 4cbb 0007 592b 2cb7 0024 b800 2159 4cb0
    0x0000170: bb00 0d59 2bb7 002c bfbb 000d 592c b700
    0x0000180: 2cbf
  Stackmap Table:
    full_frame(@110,{Top,Top,Object[#10]},{Object[#24]})
    full_frame(@208,{Top,Object[#2],Object[#10]},{Object[#24],Uninitialized[#150],Uninitialized[#150],Object[#2]})
    full_frame(@227,{Top,Object[#21]},{Object[#24],Uninitialized[#150],Uninitialized[#150],Object[#2]})
    full_frame(@231,{},{Object[#24],Object[#7]})
    full_frame(@235,{Top,Object[#2]},{Object[#24],Object[#7],Object[#7],Object[#2]})
    full_frame(@244,{Top,Object[#2],Object[#10]},{Object[#24]})
    full_frame(@307,{Top,Object[#7]},{Object[#24]})
    full_frame(@368,{Top,Object[#2]},{Object[#24]})
    full_frame(@377,{Top,Top,Object[#7]},{})

	at coursier.a.aZ.a(Unknown Source)
	at coursier.a.aY.x(Unknown Source)
	at coursier.a.aY.E(Unknown Source)
	at coursier.a.aY.y(Unknown Source)
	at coursier.a.aY.q(Unknown Source)
	at coursier.a.aY.s(Unknown Source)
	at coursier.a.dk.a(Unknown Source)
	at coursier.bT.a(Unknown Source)
	at coursier.cli.hj.<init>(Unknown Source)
	at coursier.cli.hf.g(Unknown Source)
	at coursier.cli.hi.a(Unknown Source)
	at c.f.a.b(Unknown Source)
	at b.e.c_(Unknown Source)
	at c.b.d.E.f(Unknown Source)
	at c.b.e.aK.f(Unknown Source)
	at b.f.a(Unknown Source)
	at coursier.cli.he.e(Unknown Source)
	at b.H.c_(Unknown Source)
	at c.C.h(Unknown Source)
	at b.f.a(Unknown Source)
	at coursier.cli.Coursier.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at coursier.Bootstrap.main(Bootstrap.java:387)
```

Do I need to download another pure jar?

**Comment by alexarchambault** [comment]
Add the `-noverify` option to the `java` command. That's what the launcher itself does.

That should be mentioned in the README. (Keep this issue open as a reminder.)

**Comment by fommil** [comment]
Any chance of a launcher jar, not script? Would be smaller.

**Comment by alexarchambault** [comment]
@fommil What do you mean? The bash prelude is only a few bytes long. (I have to release `1.0.0-M9` for the Java 6 branch btw, I'll do that later today.)

**Comment by fommil** [comment]
yeah but its BASE64 encoded, right?

**Comment by alexarchambault** [comment]
Hem... no:
```
$ head -2 coursier
#!/usr/bin/env sh
exec java -jar '-noverify' "$0" "$@"
```

**Comment by fommil** [comment]
ok cool, my bad

**Comment by hedefalk** [comment]
Thanks! Working fine now.

**Comment by dthboyd** [comment]
how do i do this in osx?
thanks
Then simply run the jupyter-scala script of this repository to install the kernel. Launch it with --help

**Comment by alexarchambault** [comment]
@dthboyd See the added note added by https://github.com/alexarchambault/jupyter-scala/commit/18b507d08cda47a72fdb579ee8ac33cef2b9cf81.

**Comment by dthboyd** [comment]
Ensure the coursier launcher is available in the PATH. coursier --help should print a version >= 1.0.0-M14.--------what do you mean by PATH----please clarify.

Then simply run the jupyter-scala script of this repository to install the kernel. Launch it with --help to list available (non mandatory) options.------can you let me know how to do this for osx. like step1, step2, act.
thanks.
