### ISSUE TITLE
New resolution issue with spark-hive dependencies

### ISSUE THREAD

**Issue by velvia** [alexarchambault/coursier#178]
Importing and using spark-hive 1.4.1 with coursier results in Hadoop23Shims error.   Using regular ivy / sbt does not cause the error.   I suspect Coursier is somehow resolving a different Hadoop dependency than sbt/ivy.

To reproduce:
1) clone https://github.com/tuplejump/FiloDB
2) pull latest from branch dse-4.8-spark-1.4
3) sbt spark/testOnly filodb.spark.SaveAsFiloTest

```
sbt.ForkMain$ForkError
	at org.apache.spark.sql.hive.HiveContext$.newTemporaryConfiguration(HiveContext.scala:534)
	at org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:165)
	at org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:161)
	at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:168)
	at filodb.spark.SaveAsFiloTest.<init>(SaveAsFiloTest.scala:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:646)
	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: sbt.ForkMain$ForkError: Could not load shims in class org.apache.hadoop.hive.shims.Hadoop23Shims
	at org.apache.hadoop.hive.shims.ShimLoader.createShim(ShimLoader.java:123)
	at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:115)
	at org.apache.hadoop.hive.shims.ShimLoader.getHadoopShims(ShimLoader.java:80)
	at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:248)
	at org.apache.spark.sql.hive.HiveContext$.newTemporaryConfiguration(HiveContext.scala:534)
	at org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:165)
	at org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:161)
	at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:168)
	at filodb.spark.SaveAsFiloTest.<init>(SaveAsFiloTest.scala:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:646)
	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: sbt.ForkMain$ForkError: org.apache.hadoop.hive.shims.Hadoop23Shims
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.hadoop.hive.shims.ShimLoader.createShim(ShimLoader.java:120)
	at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:115)
	at org.apache.hadoop.hive.shims.ShimLoader.getHadoopShims(ShimLoader.java:80)
	at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:248)
	at org.apache.spark.sql.hive.HiveContext$.newTemporaryConfiguration(HiveContext.scala:534)
	at org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:165)
	at org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:161)
	at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:168)
	at filodb.spark.SaveAsFiloTest.<init>(SaveAsFiloTest.scala:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:646)
	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by alexarchambault** [comment]
The origin of the problem seems to come from dependencies of `org.spark-project.hive:hive-shims:0.13.1a`, scoped as `runtime`, missing from the classpath. These are `hive-shims-0.20`, `hive-shims-0.20S`, `hive-shims-0.23`, all from organization `org.spark-project.hive.shims`. I keep investigating, but if it's only that, that should be easy to fix.

**Comment by velvia** [comment]
Thanks.
