### ISSUE TITLE
Problem when resolving dependency in scala spores

### ISSUE THREAD

**Issue by jvican** [alexarchambault/coursier#194]
Go to the project [scala spores](https://github.com/heathermiller/spores). Then, sbt in the root folder. This error message appears:
```
java.lang.NoSuchMethodError: sbt.ConfigurationReport.<init>(Ljava/lang/String;Lscala/collection/Seq;Lscala/collection/Seq;Lscala/collection/Seq;)V
	at coursier.ToSbt$$anonfun$11.apply(ToSbt.scala:163)
	at coursier.ToSbt$$anonfun$11.apply(ToSbt.scala:156)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at coursier.ToSbt$.updateReport(ToSbt.scala:156)
	at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:407)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$15.apply(Tasks.scala:418)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$15.apply(Tasks.scala:418)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:416)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:121)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) java.lang.NoSuchMethodError: sbt.ConfigurationReport.<init>(Ljava/lang/String;Lscala/collection/Seq;Lscala/collection/Seq;Lscala/collection/Seq;)V
```
When I remove `coursier` from my `plugins.sbt`, I get this and it's working:
```
[info] Loading global plugins from /home/jvican/.sbt/0.13/plugins
[info] Updating {file:/home/jvican/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Loading project definition from /data/rw/code/scala/spores/project
[info] Updating {file:/data/rw/code/scala/spores/project/}spores-build...
[info] Resolving org.scala-lang#scalap;2.10.4 ...
[info] downloading https://jcenter.bintray.com/org/scala-lang/scalap/2.10.4/scalap-2.10.4.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scalap;2.10.4!scalap.jar (960ms)
[info] Done updating.
[info] Compiling 2 Scala sources to /data/rw/code/scala/spores/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to spores (in build file:/data/rw/code/scala/spores/)
```

**Comment by alexarchambault** [comment]
The coursier SBT plugin needs SBT >= 0.13.8 (only tested with 0.13.8 and 0.13.9 actually). Changing the SBT version in `project/build.properties` addresses that.

Some need for a SBT 0.13.5 compatibility was expressed recently (by @pfn IIRC). I was thinking of maybe creating a SBT 0.13.5 specific branch of coursier, to build a compatible plugin, and maintain it until 1.0 final, if there's sufficient incentives for it...

**Comment by jvican** [comment]
Thanks @alexarchambault. I think there's no need to do that, since changing to newer versions of sbt should be the proper way to address this issue. Thanks for the heads up.
