### ISSUE TITLE
Play 2.5.1 (with SBT plugin) doesn't work

### ISSUE THREAD

**Issue by mriehl** [alexarchambault/coursier#211]
Hi,

Thank you for this project. The download / resolve speed is really amazing.
We're using coursier for play 2.4.x apps and it works without problems.

When trying to use play 2.5.1 there are strange issues however:

```
130 2016-03-31 09:43:36 mriehl@isdeblnnl084 play-bug  git:(master) 1M 1A
» bin/sbt.sh                                                                                                                                                                              FAIL
[info] Loading global plugins from /data/home/mriehl/.sbt/0.13/plugins
[info] Updating {file:/data/home/mriehl/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /data/home/mriehl/workspace/play-bug/project
Resolving default:play-bug-build:0.1-SNAPSHOT

1 error(s):
  net.java.dev.jna:jna::
    Not found: /data/home/mriehl/.sbt/0.13/plugins/target/resolution-cache/net.java.dev.jna/jna/resolved.xml.xml
    Not found
    Not found: /data/home/mriehl/.ivy2/local/net.java.dev.jna/jna/ivys/ivy.xml
    Not found: http://nexus/content/repositories/typesafe-releases/net.java.dev.jna/jna//ivys/ivy.xml
    Not found: http://nexus/content/repositories/sbt-plugin-releases/net.java.dev.jna/jna//ivys/ivy.xml
    Not found: http://nexus/content/groups/public/net/java/dev/jna/jna//jna-.pom
java.lang.Exception: Encountered 1 error(s) in dependency resolution
        at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:355)
        at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$22.apply(Tasks.scala:484)
        at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$22.apply(Tasks.scala:484)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
        at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:476)
        at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:167)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) java.lang.Exception: Encountered 1 error(s) in dependency resolution
```

I don't really know what to make of this. Any ideas on how to track it down?

**Comment by mriehl** [comment]
This is the project that generates the error: https://github.com/mriehl/play-bug

I'm running `bin/sbt.sh run`.

**Comment by alexarchambault** [comment]
The problem seems to come from `addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.2")` rather than the play plugin. I'll have a look at it later.

**Comment by alexarchambault** [comment]
https://github.com/alexarchambault/coursier/pull/213 seems to have fixed it (by chance). I added a related non-regression test for that in it (https://github.com/alexarchambault/coursier/pull/213/commits/cc0ece263df35501a6e477c76c2d6513b4e7492e).

**Comment by mriehl** [comment]
That's great, merci! Would you consider creating a new release soon? Or can you recommend building local snapshots from master, if it's stable enough?

**Comment by alexarchambault** [comment]
@mriehl Snapshots should be usable, yes. I may do a release soon though, if time allows. Beware that the organization and module name of the plugin changed (`"io.get-coursier" %% "sbt-coursier"`), and that this leads to spurious errors if the former modules (`"com.github.alexarchambault" %% "coursier-..."`) are around - the former shouldn't be added along the new ones.
