### ISSUE TITLE
Plugins  of plugin dependencies not resolved

### ISSUE THREAD

**Issue by mathieuleclaire** [alexarchambault/coursier#237]
Hi,
I get a plugin (let's say plugin 1), which depends on an other plugin (plugin2  published locally). When I compile the plugin1 with coursier, it cannot resolve the plugin2 transitive dependencies. I got something like this (sbt-osgi and scalariform are dependencies of plugin2):
(very nice project by the way !)
Mathieu

```sh
[info] Resolving default:libraries-build:0.1-SNAPSHOT
[error] 
[error] 2 error(s):
[error]   org.scalariform:sbt-scalariform:1.6.0:
[error]     /home/mathieu/.sbt/0.13/plugins/target/resolution-cache/org.scalariform/sbt-scalariform/1.6.0/resolved.xml.xml
[error]     Not found
[error]     https://repo.typesafe.com/typesafe/ivy-releases/org.scalariform/sbt-scalariform/1.6.0/ivys/ivy.xml
[error]     https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalariform/sbt-scalariform/1.6.0/ivys/ivy.xml
[error]     /home/mathieu/.ivy2/local/org.scalariform/sbt-scalariform/1.6.0/ivys/ivy.xml
[error]     https://repo1.maven.org/maven2/org/scalariform/sbt-scalariform/1.6.0/sbt-scalariform-1.6.0.pom
[error]     https://repo.scala-sbt.org/scalasbt/sbt-plugin-snapshots/org.scalariform/sbt-scalariform/1.6.0/ivys/ivy.xml
[error]     http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/org.scalariform/sbt-scalariform/1.6.0/ivys/ivy.xml
[error]     https://maven.openmole.org/public/org/scalariform/sbt-scalariform/1.6.0/sbt-scalariform-1.6.0.pom
[error]     http://repo.typesafe.com/typesafe/releases/org/scalariform/sbt-scalariform/1.6.0/sbt-scalariform-1.6.0.pom
[error]   com.typesafe.sbt:sbt-osgi:0.8.0:
[error]     /home/mathieu/.sbt/0.13/plugins/target/resolution-cache/com.typesafe.sbt/sbt-osgi/0.8.0/resolved.xml.xml
[error]     Not found
[error]     https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-osgi/0.8.0/ivys/ivy.xml
[error]     https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-osgi/0.8.0/ivys/ivy.xml
[error]     /home/mathieu/.ivy2/local/com.typesafe.sbt/sbt-osgi/0.8.0/ivys/ivy.xml
[error]     https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-osgi/0.8.0/sbt-osgi-0.8.0.pom
[error]     https://repo.scala-sbt.org/scalasbt/sbt-plugin-snapshots/com.typesafe.sbt/sbt-osgi/0.8.0/ivys/ivy.xml
[error]     http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-osgi/0.8.0/ivys/ivy.xml
[error]     https://maven.openmole.org/public/com/typesafe/sbt/sbt-osgi/0.8.0/sbt-osgi-0.8.0.pom
[error]     http://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-osgi/0.8.0/sbt-osgi-0.8.0.pom
java.lang.Exception: Encountered 2 error(s) in dependency resolution
	at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:443)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$38.apply(Tasks.scala:613)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$38.apply(Tasks.scala:613)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:605)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:192)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) java.lang.Exception: Encountered 2 error(s) in dependency resolution

```

**Comment by alexarchambault** [comment]
That looks similar to https://github.com/alexarchambault/coursier/issues/207, that is `scala_2.10` and `sbt_0.13` components seem to be missing from the paths coursier looks at. I wasn't able to reproduce https://github.com/alexarchambault/coursier/issues/207, but maybe we'll have more luck here :-)

Do you have more context? Something I could reproduce? (because the few similar examples I was able to try were fine)

**Comment by mathieuleclaire** [comment]
Hi,
It fixed my bug, thanks and sorry I didn't find time to provide you with a minimal example.
Mathieu
