### ISSUE TITLE
SBT resolution error in conjunction with ensime

### ISSUE THREAD

**Issue by mriehl** [alexarchambault/coursier#242]
Hey,

Trying to use coursier with [sbt-ensime](ensime.org).
Most things work nice and fast out of the box, but I cannot figure out a way to update the ensime server without crashing.

This creates a temporary `build.sbt` and tries to run `sbt`, which crashes.

```
[error] 3 not found
[error]   /data/home/mriehl/.ivy2/cache/org.scalaz/scalaz-concurrent_2.10/bundles/scalaz-concurrent_2.10-7.1.2.bundle
[error]   /data/home/mriehl/.ivy2/cache/org.scalaz/scalaz-core_2.10/bundles/scalaz-core_2.10-7.1.2.bundle
[error]   /data/home/mriehl/.ivy2/cache/org.scalaz/scalaz-effect_2.10/bundles/scalaz-effect_2.10-7.1.2.bundle
java.lang.Exception: Encountered 3 errors (see above messages)
        at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:574)
        at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$38.apply(Tasks.scala:613)
        at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$38.apply(Tasks.scala:613)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
        at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:605)
        at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:192)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I had a look at the ivy cache and indeed it is missing the `.bundle` files. There are `.jar` files there, but no `.bundle`. Also for some reason it's using the ivy cache and not the cache in `.coursier/cache`?

This is the `build.sbt` that ensime uses for its server update:

```
import sbt._
import IO._
import java.io._

scalaVersion := "2.11.8"
scalaBinaryVersion := "2.11"

ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }

// allows local builds of scala
resolvers += Resolver.mavenLocal

// WORKAROUND https://github.com/ensime/ensime-emacs/issues/327
// resolvers += "NetBeans" at "http://bits.netbeans.org/nexus/content/groups/netbeans"

// we need jcenter for Netbeans jars
fullResolvers += Resolver.jcenterRepo

// this is where the ensime-server snapshots are hosted
resolvers += Resolver.sonatypeRepo("snapshots")

libraryDependencies += "org.ensime" %% "ensime" % "0.9.10-SNAPSHOT"

dependencyOverrides ++= Set(
  "org.scala-lang" % "scala-compiler" % scalaVersion.value,
  "org.scala-lang" % "scala-library" % scalaVersion.value,
  "org.scala-lang" % "scala-reflect" % scalaVersion.value,
  "org.scala-lang" % "scalap" % scalaVersion.value
)

val saveClasspathTask = TaskKey[Unit]("saveClasspath", "Save the classpath to a file")

saveClasspathTask := {
  val managed = (managedClasspath in Runtime).value.map(_.data.getAbsolutePath)
  val unmanaged = (unmanagedClasspath in Runtime).value.map(_.data.getAbsolutePath)
  val out = file("/data/home/mriehl/.emacs.d/ensime/classpath_2.11.8_0.9.10-SNAPSHOT")
  write(out, (unmanaged ++ managed).mkString(File.pathSeparator))
}
```

I'm grateful for any pointers or ideas you have to get to the bottom of this issue.

**Comment by alexarchambault** [comment]
The line
```scala
fullResolvers += Resolver.jcenterRepo
```
should be changed to
```scala
resolvers += Resolver.jcenterRepo
```
The coursier plugin doesn't expect resolvers to be put in `fullResolvers` (`resolvers` is the standard way of adding a resolver anyway).

What versions of sbt-ensime / coursier are you using then? Thowing this file in a directory, along with a `sbt.version=0.13.11` in `project/build.properties`, and having the coursier (`1.0.0-M11-1`) and ensime (`0.5.0`) SBT plugin set up in `~/.sbt/0.13/plugins/build.sbt` works fine for me. Both plugins were always around on my machine, without any notable issue.

**Comment by alexarchambault** [comment]
About `fullResolvers` in the ensime server config, see the discussion around https://github.com/ensime/ensime-server/pull/1312#issuecomment-192643947.

**Comment by mriehl** [comment]
Yes, my issue is that people seem to be using ensime and coursier with no issues. So I think this might be related to something I did or didn't do with my global sbt configuration.

I have coursier `1.0.0-M11-1` (from `io.get-coursier`) and sbt-ensime `0.5.0` (but fails with the same error when using `0.4.0`).

**Comment by mriehl** [comment]
Tried switching the line to `resolvers` but I still get the errors.

Removed the ivy cache to see if it's an issue that would go away on a new machine. What I don't really understand is why the output looks like ivy is downloading the dependencies:

```
[info] Loading global plugins from /data/home/mriehl/.sbt/0.13/plugins
[info] Updating {file:/data/home/mriehl/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.10/7.1.2/scalaz-core_2.10-7.1.2.jar ...
[info]  [SUCCESSFUL ] org.scalaz#scalaz-core_2.10;7.1.2!scalaz-core_2.10.jar(bundle) (1034ms)
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-concurrent_2.10/7.1.2/scalaz-concurrent_2.10-7.1.2.jar ...
[info]  [SUCCESSFUL ] org.scalaz#scalaz-concurrent_2.10;7.1.2!scalaz-concurrent_2.10.jar(bundle) (119ms)
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-effect_2.10/7.1.2/scalaz-effect_2.10-7.1.2.jar ...
[info]  [SUCCESSFUL ] org.scalaz#scalaz-effect_2.10;7.1.2!scalaz-effect_2.10.jar(bundle) (136ms)
[info] Done updating.
[info] Loading project definition from /tmp/ensime_update_1076nRB/project
[info] Resolving default:ensime_update_1076nrb-build:0.1-SNAPSHOT
[info] Resolution done
[info] Fetching artifacts
[info] Fetching artifacts: done
[error] 3 not found
[error]   /data/home/mriehl/.ivy2/cache/org.scalaz/scalaz-concurrent_2.10/bundles/scalaz-concurrent_2.10-7.1.2.bundle
[error]   /data/home/mriehl/.ivy2/cache/org.scalaz/scalaz-core_2.10/bundles/scalaz-core_2.10-7.1.2.bundle
[error]   /data/home/mriehl/.ivy2/cache/org.scalaz/scalaz-effect_2.10/bundles/scalaz-effect_2.10-7.1.2.bundle
java.lang.Exception: Encountered 3 errors (see above messages)
        at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:574)
        at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$38.apply(Tasks.scala:613)
[...]
```

**Comment by mriehl** [comment]
Huh. I think I finally fixed it.

I had two repository files in my `~/.sbt`.

* A `~/.sbt/repo` (which I created, has a `cache` entry for working offline with ivy)
* A `~/.sbt/repositories`. I think this was created by `activator` at some point because there are activator entries there.

Removing the `~/.sbt/repositories` fixes my problem. The ensime server update works without issues now.

For the record these were the contents of the `repositories` file:

```
[repositories]
  local
  activator-launcher-local: file://${activator.local.repository-${activator.home-${user.home}/.activator}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  activator-local: file://${activator.local.repository-/data/home/mriehl/programs/activator-dist-1.3.7/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central
  typesafe-releases: http://repo.typesafe.com/typesafe/releases
  typesafe-ivy-releasez: http://repo.typesafe.com/typesafe/ivy-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  cache: file:///data/home/mriehl/.ivy2/cache, [organisation]/[module]/ivy-[revision].xml, [organisation]/[module]/[type]s/[module]-[revision].[type]
  global-nex-typesafe: http://nexus.rz.is/content/repositories/typesafe-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  global-nex-sbt-plugins: http://nexus.rz.is/content/repositories/sbt-plugin-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  global-nex: http://nexus.rz.is/content/groups/public/
```

(nexus.rz.is is an enterprise nexus installation that we use)
