### ISSUE TITLE
java.lang.NoSuchMethodError: sbt.Keys$.excludeDependencies()Lsbt/SettingKey;

### ISSUE THREAD

**Issue by mathieuleclaire** [alexarchambault/coursier#245]
Hi,
when I try to build a multi-project, I got the following error. It seems to crash in coursier directly. I tried with sbt 0.13.8 and 0.13.11 with the same result.
Thanks

[info] Loading global plugins from /home/mathieu/.sbt/0.13/plugins
java.lang.NoSuchMethodError: sbt.Keys$.excludeDependencies()Lsbt/SettingKey;
	at coursier.Tasks$.updateTask(Tasks.scala:266)
	at coursier.CoursierPlugin$.projectSettings$lzycompute(CoursierPlugin.scala:43)
	at coursier.CoursierPlugin$.projectSettings(CoursierPlugin.scala:32)
	at sbt.Load$$anonfun$autoPluginSettings$1$1.apply(Load.scala:517)
	at sbt.Load$$anonfun$autoPluginSettings$1$1.apply(Load.scala:517)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at sbt.Load$.autoPluginSettings$1(Load.scala:517)
	at sbt.Load$.sbt$Load$$expand$1(Load.scala:525)
	at sbt.Load$$anonfun$sbt$Load$$expand$1$2.apply(Load.scala:526)
	at sbt.Load$$anonfun$sbt$Load$$expand$1$2.apply(Load.scala:526)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
	at sbt.Load$.sbt$Load$$expand$1(Load.scala:526)
	at sbt.Load$.loadSettings(Load.scala:528)
	at sbt.Load$.sbt$Load$$loadSbtFiles$1(Load.scala:464)
	at sbt.Load$$anonfun$loadForProjects$1$1.apply(Load.scala:470)
	at sbt.Load$$anonfun$loadForProjects$1$1.apply(Load.scala:465)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Load$.loadForProjects$1(Load.scala:465)
	at sbt.Load$.loadTransitive(Load.scala:480)
	at sbt.Load$.loadProjects$1(Load.scala:418)
	at sbt.Load$.loadUnit(Load.scala:429)
	at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
	at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:92)
	at sbt.BuildLoader.apply(BuildLoader.scala:143)
	at sbt.Load$.loadAll(Load.scala:312)
	at sbt.Load$.loadURI(Load.scala:264)
	at sbt.Load$.load(Load.scala:260)
	at sbt.Load$.load(Load.scala:251)
	at sbt.Load$.apply(Load.scala:134)
	at sbt.Load$.defaultLoad(Load.scala:37)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:473)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
	at sbt.Command$.process(Command.scala:95)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
	at sbt.State$$anon$1.process(State.scala:179)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.MainLoop$.next(MainLoop.scala:100)
	at sbt.MainLoop$.run(MainLoop.scala:93)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
	at sbt.Using.apply(Using.scala:25)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
	at sbt.MainLoop$.runLogged(MainLoop.scala:25)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:19)
	at xsbt.boot.Boot$.runImpl(Boot.scala:44)
	at xsbt.boot.Boot$.main(Boot.scala:20)
	at xsbt.boot.Boot.main(Boot.scala)

**Comment by alexarchambault** [comment]
I usually get those when trying to use coursier with sbt < 0.13.8... Do you have a minimal repro?

**Comment by mathieuleclaire** [comment]
Could it be possible that it occurs with one of the dependencies of my project (which could be potetially in sbt < 0.13.8)?

**Comment by mathieuleclaire** [comment]
You can reproduce with a simple project with just a build.sbt fails because of the dependency scalajs-dom, which depends on sbt 0.13.7.

```sh
organization := "fr.iscpif"

name := "testCoursier"

version := "0.1.0-SNAPSHOT"

scalaVersion := "2.11.8"

resolvers ++= Seq(
  DefaultMavenRepository
)

libraryDependencies ++= Seq(
  "org.scala-js" %% "scalajs-dom" % "0.9.0"
)
```

**Comment by mathieuleclaire** [comment]
Actually, in this examble, it occurs because I did not specified in build.properties the sbt version. But in my project, I depends on sbt 0.13.8 and I depend on scalajs-dom, which depends on sbt 0.13.7.

**Comment by alexarchambault** [comment]
I wasn't able to reproduce that with the `build.sbt` you give. It must lack some context (scalajs-dom is a scalajs lib, so requires `%%%`, the scalajs SBT plugin, and a scalajs project too... Plus it doesn't depend on sbt it seems.)

**Comment by felixt-cake** [comment]
Found something similar with this type of build file:

```
name := "something-for-my-client"

organization := "com.myclient"

version := "0.1.0-SNAPSHOT"

scalaVersion := "2.11.8"

resolvers += "Client Artifactory" at "http://notgreattosharehere.com/..."

libraryDependencies ++= Seq(
  "org.apache.commons"          % "commons-lang3"     % "3.4"     % "compile",
  "org.json4s"                 %% "json4s-native"     % "3.2.11"  % "compile",
  "com.typesafe.play"          %% "play-test"         % "2.3.9"   % "test"
)

//----scalastyle----
lazy val compileScalastyle = taskKey[Unit]("compileScalastyle")

lazy val testScalastyle = taskKey[Unit]("testScalastyle")

compileScalastyle := org.scalastyle.sbt.ScalastylePlugin.scalastyle.in(Compile).toTask("").value

testScalastyle := org.scalastyle.sbt.ScalastylePlugin.scalastyle.in(Test).toTask("").value

(compile in Compile) <<= (compile in Compile) dependsOn compileScalastyle

(test in Test) <<= (test in Test) dependsOn testScalastyle

//----end scalastyle----

fork in Test := false
parallelExecution in Test := false
scalacOptions in ThisBuild ++= Seq("-unchecked", "-deprecation")
```

**Comment by felixt-cake** [comment]
I'm using sbt 0.13.9.

**Comment by felixt-cake** [comment]
I ran into this issue, and was able to fix it by writing a `project/build.properties` file which looked like this:

```
sbtVersion=0.13.9
```

**Comment by felixt-cake** [comment]
Thanks for providing a really useful plugin!

**Comment by pbalm** [comment]
I had this problem too and I was able to solve it by upgrading my sbt-launch.jar from 0.13.5 to 0.13.11.

**Comment by alexarchambault** [comment]
Closing this. Re-open if it still doesn't work.
