### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by schleumer** [alexarchambault/coursier#250]
While building a Play Framework project i'm getting some `Not Found` errors, these errors are "random" everytime i delete cache directories the packages on log are different

log:
```
[error] 
[error] 3 error(s):
[error]   com.typesafe.sbtrc:client-2-11:0.3.1:
[error]     /home/schleumer/.sbt/0.13/plugins/target/resolution-cache/com.typesafe.sbtrc/client-2-11/0.3.1/resolved.xml.xml
[error]     Not found
[error]     /home/schleumer/.ivy2/local/com.typesafe.sbtrc/client-2-11/0.3.1/ivys/ivy.xml
[error]     https://repo1.maven.org/maven2/com/typesafe/sbtrc/client-2-11/0.3.1/client-2-11-0.3.1.pom
[error]     http://dl.bintray.com/scalaz/releases/com/typesafe/sbtrc/client-2-11/0.3.1/client-2-11-0.3.1.pom
[error]     https://jcenter.bintray.com/com/typesafe/sbtrc/client-2-11/0.3.1/client-2-11-0.3.1.pom
[error]   com.typesafe.sbtrc:actor-client-2-11:0.3.1:
[error]     /home/schleumer/.sbt/0.13/plugins/target/resolution-cache/com.typesafe.sbtrc/actor-client-2-11/0.3.1/resolved.xml.xml
[error]     Not found
[error]     /home/schleumer/.ivy2/local/com.typesafe.sbtrc/actor-client-2-11/0.3.1/ivys/ivy.xml
[error]     https://repo1.maven.org/maven2/com/typesafe/sbtrc/actor-client-2-11/0.3.1/actor-client-2-11-0.3.1.pom
[error]     http://dl.bintray.com/scalaz/releases/com/typesafe/sbtrc/actor-client-2-11/0.3.1/actor-client-2-11-0.3.1.pom
[error]     https://jcenter.bintray.com/com/typesafe/sbtrc/actor-client-2-11/0.3.1/actor-client-2-11-0.3.1.pom
[error]   net.contentobjects.jnotify:jnotify:0.94-play-1:
[error]     /home/schleumer/.sbt/0.13/plugins/target/resolution-cache/net.contentobjects.jnotify/jnotify/0.94-play-1/resolved.xml.xml
[error]     Not found
[error]     /home/schleumer/.ivy2/local/net.contentobjects.jnotify/jnotify/0.94-play-1/ivys/ivy.xml
[error]     https://repo1.maven.org/maven2/net/contentobjects/jnotify/jnotify/0.94-play-1/jnotify-0.94-play-1.pom
[error]     http://dl.bintray.com/scalaz/releases/net/contentobjects/jnotify/jnotify/0.94-play-1/jnotify-0.94-play-1.pom
[error]     https://jcenter.bintray.com/net/contentobjects/jnotify/jnotify/0.94-play-1/jnotify-0.94-play-1.pom
java.lang.Exception: Encountered 3 error(s) in dependency resolution
	at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:443)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$38.apply(Tasks.scala:613)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$38.apply(Tasks.scala:613)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:605)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:192)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (root/*:update) java.lang.Exception: Encountered 3 error(s) in dependency resolution
[error] Total time: 7 s, completed May 13, 2016 6:20:24 PM
```

**Comment by schleumer** [comment]
Solved some of errros adding:

```
resolvers ++= Seq(
  "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/",
  Resolver.url("Typesafe Ivy releases", url("https://repo.typesafe.com/typesafe/ivy-releases"))(Resolver.ivyStylePatterns)
)
```

To `build.sbt`, now the only error left is:

```
[error] 
[error] 1 error(s):
[error]   net.contentobjects.jnotify:jnotify:0.94-play-1:
[error]     /home/schleumer/.sbt/0.13/plugins/target/resolution-cache/net.contentobjects.jnotify/jnotify/0.94-play-1/resolved.xml.xml
[error]     Not found
[error]     /home/schleumer/.ivy2/local/net.contentobjects.jnotify/jnotify/0.94-play-1/ivys/ivy.xml
[error]     https://repo1.maven.org/maven2/net/contentobjects/jnotify/jnotify/0.94-play-1/jnotify-0.94-play-1.pom
[error]     http://repo.typesafe.com/typesafe/releases/net/contentobjects/jnotify/jnotify/0.94-play-1/jnotify-0.94-play-1.pom
[error]     https://repo.typesafe.com/typesafe/ivy-releases/net.contentobjects.jnotify/jnotify/0.94-play-1/ivys/ivy.xml
[error]     http://dl.bintray.com/scalaz/releases/net/contentobjects/jnotify/jnotify/0.94-play-1/jnotify-0.94-play-1.pom
[error]     https://jcenter.bintray.com/net/contentobjects/jnotify/jnotify/0.94-play-1/jnotify-0.94-play-1.pom
java.lang.Exception: Encountered 1 error(s) in dependency resolution
	at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:443)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$38.apply(Tasks.scala:613)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$38.apply(Tasks.scala:613)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:605)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:192)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (root/*:update) java.lang.Exception: Encountered 1 error(s) in dependency resolution
```

**Comment by schleumer** [comment]
Solved the last error with the following ivy resolver:

```
resolvers += Resolver.url("sbt-plugins-releases", url("https://dl.bintray.com/playframework/sbt-plugin-releases"))(Resolver.ivyStylePatterns),
```

Play Framework injects some kind of magic resolvers?

**Comment by schleumer** [comment]
It's O.K. now.
