### ISSUE TITLE
Maximum number of iteration of dependency resolution reached

### ISSUE THREAD

**Issue by FloWi** [alexarchambault/coursier#275]
We have a relatively large build.sbt with lots of dependencies.
I encountered this bug after adding another dependency.

Do you know what could be wrong?
I can't reproduce it with a smaller build.sbt.

If you need further input, I'll try to assemble a small example.

```
java.lang.Exception: Maximum number of iteration of dependency resolution reached
	at coursier.Tasks$$anonfun$resolutionTask$1.coursier$Tasks$$anonfun$$resolution$1(Tasks.scala:469)
	at coursier.Tasks$$anonfun$resolutionTask$1$$anonfun$apply$35.apply(Tasks.scala:508)
	at coursier.Tasks$$anonfun$resolutionTask$1$$anonfun$apply$35.apply(Tasks.scala:508)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:501)
	at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:227)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (kafka-consumer/*:coursierResolution) java.lang.Exception: Maximum number of iteration of dependency resolution reached
```

**Comment by alexarchambault** [comment]
Two possibilities:
- either it actually is a tricky resolution requiring more than the default 50 max iterations (I arbitrarily set it to twice the number of iterations of a tricky one I had at some point), or
- it's a bug in coursier that makes the resolution not converge, thus reaching the maximum number of iterations.

To check, you can increase the max number of iterations via the `coursierMaxIterations` key. Something like `coursierMaxIterations := 200` (or even more) in the `kafka-consumer` (sub-)project should do.

If it does converge for a higher max, we'll know it's the latter case...

**Comment by FloWi** [comment]
Thanks for your feedback. I tried it with the increased max number of iterations and it works like a charm again :) Great - I love your tool - such a huge timesaver!

**Comment by antonkulaga** [comment]
I have the same stupid error at quite simple https://github.com/antonkulaga/CRISPR project

**Comment by antonkulaga** [comment]
Please, change the defaults to 200, as 50 is too low and is exceeded even in quite simple projects

**Comment by Diliprajgor** [comment]
where to set the coursierMaxIterations := 200 ? i tried setting in build.sbt. i am getting syntax error.
