### ISSUE TITLE
file does not resolve

### ISSUE THREAD

**Issue by antonkulaga** [alexarchambault/coursier#300]
In ly project ( https://github.com/antonkulaga/bio-nlp ) I had to fall back to ivy from coursier because of the following resolution error:

``` bash
root Listening for transport dt_socket at address: 5005
> root[ERROR] Error: A JNI error has occurred, please check your installation and try again
root[ERROR] Exception in thread "main" java.lang.NoClassDefFoundError: better/files/File
root[ERROR]     at java.lang.Class.getDeclaredMethods0(Native Method)
root[ERROR]     at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
root[ERROR]     at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
root[ERROR]     at java.lang.Class.getMethod0(Class.java:3018)
root[ERROR]     at java.lang.Class.getMethod(Class.java:1784)
root[ERROR]     at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
root[ERROR]     at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
root[ERROR] Caused by: java.lang.ClassNotFoundException: better.files.File
root[ERROR]     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
root[ERROR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
root[ERROR]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
root[ERROR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
root[ERROR]     ... 7 more
root ... finished with exit code 1
```

**Comment by alexarchambault** [comment]
With https://github.com/alexarchambault/coursier/pull/304 and the current master of bio-nlp (https://github.com/antonkulaga/bio-nlp/commit/de711ef08940cc296d667b16cc3a847b445968ac), and either removing or marking as `pomOnly()` [this dependency](https://github.com/antonkulaga/bio-nlp/blob/master/project/Dependencies.scala#L81), it compiles fine (`sbt compile`)

**Comment by alexarchambault** [comment]
Closing this. Re-open if you have more details.
