### ISSUE TITLE
Possible issue with snapshot version metadata

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#307]
Discussed by @emanresusername on gitter around [this message](https://gitter.im/alexarchambault/coursier?at=578bde4ed11cd288123e7e87). It's possibly already fixed in the current master (https://github.com/alexarchambault/coursier/commit/3c7d3b844330a98b5cb13149ab0b0097b3a982e5), I'd like to check that again.

**Comment by emanresusername** [comment]
follow up for `1.0.0-M13`, not sure if this is related, but found in the same project as the last one.
can repro with this minimal `build.sbt`
```scala
scalaVersion := "2.11.8"
libraryDependencies ++= Seq(
  "com.novus"      %% "salat"        % "1.9.9"
)
```
get this error
```text
[info] Loading global plugins from ~/.sbt/0.13/plugins
[info] Set current project to test (in build file:/private/tmp/test/)
[success] Total time: 0 s, completed Aug 7, 2016 2:10:00 AM
[info] ENSIME update.
[info] Updating default:test_2.11:0.1-SNAPSHOT
[info] Resolved default:test_2.11:0.1-SNAPSHOT dependencies
[info] Fetching artifacts of default:test_2.11:0.1-SNAPSHOT
[info] Fetched artifacts of default:test_2.11:0.1-SNAPSHOT
coursier.ResolutionException: 1 not found  https://repo1.maven.org/maven2/com/novus/salat_2.11/1.9.9/salat_2.11-1.9.9.jar
[error] (*:update) coursier.ResolutionException: 1 not found  https://repo1.maven.org/maven2/com/novus/salat_2.11/1.9.9/salat_2.11-1.9.9.jar
[error] Missing task key: Runs the aggregated UpdateReport for `update' and `updateClassifiers' respectively.
java.lang.IllegalArgumentException
	at org.ensime.CommandSupport$.org$ensime$CommandSupport$$fail(EnsimePlugin.scala:699)
	at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:714)
	at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:714)
	at scala.Option.getOrElse(Option.scala:120)
	at org.ensime.CommandSupport$RichTaskKey.run(EnsimePlugin.scala:714)
	at org.ensime.EnsimePlugin$$anonfun$ensimeConfig$1.apply(EnsimePlugin.scala:355)
	at org.ensime.EnsimePlugin$$anonfun$ensimeConfig$1.apply(EnsimePlugin.scala:319)
	at sbt.Command$$anonfun$sbt$Command$$apply1$1$$anonfun$apply$6.apply(Command.scala:71)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:54)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.IllegalArgumentException
[error] Use 'last' for the full log.
```

**Comment by emanresusername** [comment]
with `M14` `salat` fixed but `flapdoodle` back broken
```scala
scalaVersion := "2.11.8"
libraryDependencies ++= Seq(
  "com.novus"      %% "salat"        % "1.9.9",
  "de.flapdoodle.embed"         % "de.flapdoodle.embed.process" % "1.50.3-SNAPSHOT" % "test",
  "de.flapdoodle.embed"         % "de.flapdoodle.embed.mongo"   % "1.50.6-SNAPSHOT" % "test"
)
resolvers ++= Seq(
  "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
)
```
```text
coursier.ResolutionException: 2 not found
  https://oss.sonatype.org/content/repositories/snapshots/de/flapdoodle/embed/de.flapdoodle.embed.mongo/1.50.6-SNAPSHOT/de.flapdoodle.embed.mongo-1.50.6-SNAPSHOT.jar
  https://oss.sonatype.org/content/repositories/snapshots/de/flapdoodle/embed/de.flapdoodle.embed.process/1.50.3-SNAPSHOT/de.flapdoodle.embed.process-1.50.3-SNAPSHOT.jar
[error] (*:update) coursier.ResolutionException: 2 not found
[error]   https://oss.sonatype.org/content/repositories/snapshots/de/flapdoodle/embed/de.flapdoodle.embed.mongo/1.50.6-SNAPSHOT/de.flapdoodle.embed.mongo-1.50.6-SNAPSHOT.jar
[error]   https://oss.sonatype.org/content/repositories/snapshots/de/flapdoodle/embed/de.flapdoodle.embed.process/1.50.3-SNAPSHOT/de.flapdoodle.embed.process-1.50.3-SNAPSHOT.jar
```

**Comment by emanresusername** [comment]
the above still stands, but this new thing popped up in the `M14-3` milestone for me in another project
```text
java.lang.NoSuchMethodError: fastparse.all$.parserApi(Ljava/lang/Object;Lscala/Function1;)Lfastparse/ParserApi;
	at coursier.ivy.PropertiesPattern$Parser$.<init>(Pattern.scala:127)
	at coursier.ivy.PropertiesPattern$Parser$.<clinit>(Pattern.scala)
	at coursier.ivy.PropertiesPattern$.parser(Pattern.scala:142)
	at coursier.ivy.PropertiesPattern$.parse(Pattern.scala:146)
	at coursier.Tasks$.coursier$Tasks$$globalPluginPattern$lzycompute(Tasks.scala:300)
	at coursier.Tasks$.coursier$Tasks$$globalPluginPattern(Tasks.scala:281)
	at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:460)
	at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:317)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
can't share the exact `build.sbt` of that project, but lmk if it'd be helpful to try to widdle that down to a shareable, minimal `build.sbt` and i can give that a go

**Comment by alexarchambault** [comment]
The `ResolutionException `s seem to originate from https://github.com/alexarchambault/coursier/issues/169. (Keeping the discussion there).

About the `NoSuchMethodError`, another plugin should pull another (incompatible) version of fastparse.
