### ISSUE TITLE
Dependency resolution error with overridden sbt paths

### ISSUE THREAD

**Issue by durban** [alexarchambault/coursier#317]
If I run sbt with non-default paths, by setting the `sbt.global.base`, `sbt.boot.directory` and `sbt.ivy.home ` system properties, dependency resolution fails with an error like this (immediately when starting sbt):
```
[error] 4 error(s):
[error]   org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
[error]     not found: /home/daurban/tmp/bug/hm/.sbt/0.13/plugins/target/resolution-cacheorg.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/resolved.xml.xml
[error]     Not found
[error]     not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: /home/daurban/tmp/bug/hm/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: https://jcenter.bintray.com/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]     not found: https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]   org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
[error]     not found: /home/daurban/tmp/bug/hm/.sbt/0.13/plugins/target/resolution-cacheorg.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/resolved.xml.xml
[error]     Not found
[error]     not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: /home/daurban/tmp/bug/hm/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: https://jcenter.bintray.com/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]     not found: https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]   org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
[error]     not found: /home/daurban/tmp/bug/hm/.sbt/0.13/plugins/target/resolution-cacheorg.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/resolved.xml.xml
[error]     Not found
[error]     not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: /home/daurban/tmp/bug/hm/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: https://jcenter.bintray.com/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]     not found: https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]   org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
[error]     not found: /home/daurban/tmp/bug/hm/.sbt/0.13/plugins/target/resolution-cacheorg.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/resolved.xml.xml
[error]     Not found
[error]     not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: /home/daurban/tmp/bug/hm/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]     not found: https://jcenter.bintray.com/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]     not found: https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
java.lang.Exception: Encountered 4 error(s) in dependency resolution
        at coursier.Tasks$$anonfun$resolutionTask$1.coursier$Tasks$$anonfun$$resolution$1(Tasks.scala:534)
        at coursier.Tasks$$anonfun$resolutionTask$1$$anonfun$apply$34.apply(Tasks.scala:550)
        at coursier.Tasks$$anonfun$resolutionTask$1$$anonfun$apply$34.apply(Tasks.scala:550)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
        at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:543)
        at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:228)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:coursierResolution) java.lang.Exception: Encountered 4 error(s) in dependency resolution
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

A possible reason might be that here: https://github.com/alexarchambault/coursier/blob/master/plugin/src/main/scala-2.10/coursier/Tasks.scala#L404 the `globalPluginsRepo` uses a path constructed form the `user.home` system property (and not the `sbt.global.base` property). Please also note, that the error message refers to a path `/home/daurban/tmp/bug/hm/.sbt/0.13/plugins/target/resolution-cacheorg.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/resolved.xml.xml`. There seems to be 2 problems with this: (1) its under `user.home` as noted above; and (2) there seem to be a slash ("/") missing (after `resolution-cache` and before `org.scala-sbt`).

Please also note, that on the machine I tried this, the default paths (derived from `user.home`) *does not* contain valid sbt directories.

**Comment by alexarchambault** [comment]
https://github.com/alexarchambault/coursier/commit/908a596b6d2330e66cd3ae5dd4fe6318d7828f7f should fix that. It will be included with 1.0.0-M14, that should be released in a few hours.

**Comment by durban** [comment]
Indeed, this seems to be fixed in 1.0.0-M14. Thanks!

**Comment by avdv** [comment]
Hi,

I was running into a similar issue as I was trying to start SBT in a coursier checkout:

```
[info] Resolved coursier-build-build dependencies
coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
  org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
    not found:
      https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      /home/claudio/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
      https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error] (*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]   org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       /home/claudio/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]       https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r
```

The reason, apparently, was that I had deleted the `~/.sbt/0.13/plugins/target` directory because of an Ensime issue (ensime/ensime-sbt#280) even after removing the Ensime SBT plugin from my global plugins.

So, in order to build coursier, you need to initially run SBT in another project in order to seed the `~/.sbt/0.13/plugins/target/resolution-cache` folder.

**Comment by smcinerney** [comment]
@alexarchambault I just hit this with current version.

**Comment by olafurpg** [comment]
I hit on this problem as well. The problem was that I was using two different versions of coursier in `project/plugins.sbt` and `project/project/plugins.sbt`. The problem was fixed by using the same version in both places
```scala
// project/project/plugins.sbt
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.2")
// project/plugins.sbt
addSbtPlugin("io.get-coursier" % "sbt-coursier" % coursier.util.Properties.version)
```
