### ISSUE TITLE
sbteclipse fails to create eclipse project

### ISSUE THREAD

**Issue by HairyFotr** [alexarchambault/coursier#342]
I tried to create an eclipse project using sbteclipse in my `plugins.sbt`:

    addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")

Running `sbt eclipse` works without Coursier, but with Coursier there is some missing scalaz code:

    [info] Loading global plugins from /home/hairy/.sbt/0.13/plugins
    [info] Updating {file:/home/hairy/.sbt/0.13/plugins/}global-plugins...
    [info] Resolving org.fusesource.jansi#jansi;1.4 ...
    [info] Done updating.
    [info] Set current project to eclipse (in build file:/home/hairy/dev/coursierTests/eclipse/)
    [info] About to create Eclipse project files for your project(s).
    java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationOps(Ljava/lang/Object;)Lscalaz/syntax/ValidationOps;
	    at com.typesafe.sbteclipse.core.EclipsePlugin$EclipseRewriteRuleTransformerFactory$ClasspathDefault$.createTransformer(EclipsePlugin.scala:390)
	    at com.typesafe.sbteclipse.core.Eclipse$$anonfun$6$$anonfun$apply$4$$anonfun$7.apply(Eclipse.scala:128)
	    at com.typesafe.sbteclipse.core.Eclipse$$anonfun$6$$anonfun$apply$4$$anonfun$7.apply(Eclipse.scala:128)
	    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	    at scala.collection.immutable.List.foreach(List.scala:318)
	    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	    at com.typesafe.sbteclipse.core.Eclipse$$anonfun$6$$anonfun$apply$4.apply(Eclipse.scala:128)
	    at com.typesafe.sbteclipse.core.Eclipse$$anonfun$6$$anonfun$apply$4.apply(Eclipse.scala:122)
	    at scala.Option$WithFilter.map(Option.scala:206)
	    at com.typesafe.sbteclipse.core.Eclipse$$anonfun$6.apply(Eclipse.scala:122)
	    at com.typesafe.sbteclipse.core.Eclipse$$anonfun$6.apply(Eclipse.scala:121)
	    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	    at com.typesafe.sbteclipse.core.Eclipse$.handleProjects(Eclipse.scala:121)
	    at com.typesafe.sbteclipse.core.Eclipse$.action(Eclipse.scala:105)
	    at com.typesafe.sbteclipse.core.Eclipse$$anonfun$eclipseCommand$2.apply(Eclipse.scala:86)
	    at com.typesafe.sbteclipse.core.Eclipse$$anonfun$eclipseCommand$2.apply(Eclipse.scala:86)
	    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	    at sbt.Command$.process(Command.scala:93)
	    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	    at sbt.State$$anon$1.process(State.scala:184)
	    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	    at sbt.MainLoop$.next(MainLoop.scala:96)
	    at sbt.MainLoop$.run(MainLoop.scala:89)
	    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	    at sbt.Using.apply(Using.scala:24)
	    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	    at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	    at sbt.StandardMain$.runManaged(Main.scala:54)
	    at sbt.xMain.run(Main.scala:29)
	    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	    at xsbt.boot.Launch$.run(Launch.scala:109)
	    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	    at xsbt.boot.Launch$.launch(Launch.scala:117)
	    at xsbt.boot.Launch$.apply(Launch.scala:18)
	    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	    at xsbt.boot.Boot$.main(Boot.scala:17)
	    at xsbt.boot.Boot.main(Boot.scala)
    [error] java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationOps(Ljava/lang/Object;)Lscalaz/syntax/ValidationOps;

**Comment by alexarchambault** [comment]
That's because of sbteclipse depending on scalaz 7.1... Same as https://github.com/typesafehub/sbteclipse/issues/221#issuecomment-230298325.

I opened https://github.com/typesafehub/sbteclipse/pull/321 to propose to fix that in sbteclipse.

**Comment by benmccann** [comment]
@alexarchambault thanks for the PR. I just merged it and will try to cut a new sbteclipse release

**Comment by benmccann** [comment]
sbteclipse 5.0.1 released. This issue can be closed now
