### ISSUE TITLE
launcher app

### ISSUE THREAD

**Issue by fommil** [alexarchambault/coursier#69]
in ensime we are using sbt to bootstrap downloading the server and getting its classpath so that we can start it.

It occurs to me that if there was a really minimal jar app (e.g. built with proguard) based on this library, which could take a set of basic maven artefacts rules (including overrides), then it should be possible to download all the ensime jars and extract the classpath. This has general appeal. We could even distribute that jar with ensime emacs/vim/sublime/atom etc and really simplify the startup.

**Comment by alexarchambault** [comment]
It's almost there! :-) The `launch` command (`sbt cli/pack; cli/target/pack/bin/coursier launch --help`) aims at doing that, but a few things require fixing in it (it messes coursier dependencies with the ones of the app to launch, e.g. doing `cli/target/pack/bin/coursier launch com.lihaoyi:ammonite-repl_2.11.7:0.4.8 -M ammonite.repl.Repl` works at first, but typing `case class CC(i: Int); CC(3)` makes it crash.)

One thing you can do instead is create a bootstrap JAR, like
```
cli/target/pack/bin/coursier bootstrap com.lihaoyi:ammonite-repl_2.11.7:0.4.8 -M ammonite.repl.Repl -D "\$HOME/.bootstrap" -o bootstrap.jar
```

This creates `bootstrap.jar` (`-o bootstrap.jar`), a minimal app that will fetch the required dependencies (from Central, etc.), put them in `$HOME/.bootstrap`, then launch `ammonite.repl.Repl` (`-M ammonite.repl.Repl`) from it.

The `bootstrap` command actually allows to create a JAR of coursier with a working `launcher` command (TODO though).

**Comment by alexarchambault** [comment]
@fommil As soon as https://github.com/alexarchambault/coursier/pull/85 gets merged and pushed to Sonatype, the following should just work (it does for me locally):
```
$ ./coursier fetch \
    -r file://$HOME/.m2/repository \
    -r central \
    -r http://bits.netbeans.org/nexus/content/groups/netbeans \
    -r https://oss.sonatype.org/content/repositories/snapshots \
      org.ensime:ensime_2.11:0.9.10-SNAPSHOT \
        -V org.scala-lang:scala-compiler:2.11.6 \
        -V org.scala-lang:scala-library:2.11.6 \
        -V org.scala-lang:scala-reflect:2.11.6 \
        -V org.scala-lang:scalap:2.11.6
```
It prints on stdout a list of (local) JAR files (and only that, all the other messages go to stderr). Replace `fetch` by `classpath` to get something on a single line that can be handed directly to `java -cp`.

There are still some small glitches in coursier you should be aware of, like:
- snapshot dependencies, once in cache, don't get updated automatically (https://github.com/alexarchambault/coursier/issues/41),
- and file locking could be better too (https://github.com/alexarchambault/coursier/issues/71), if ever you launch two coursier processes in parallel (but a single resolution then fetching its artifacts shouldn't be a problem).

I'll close this issue as soon as https://github.com/alexarchambault/coursier/pull/85 is merged, because... now the launcher is there...

**Comment by alexarchambault** [comment]
Also, look carefully at the generated list of JARs, and maybe compare it with one generated by SBT? Just in case.

**Comment by fommil** [comment]
:-) we'll need snapshots to update as we do rolling releases. Looking good!

**Comment by fommil** [comment]
BTW can you please make sure that your binary that's your LICENSE file in it?

**Comment by alexarchambault** [comment]
@fommil You mean, putting a note about the license in the launcher?

Can you confirm that the generated list of JARs is the same as SBT? There are netbeans artifacts pulled transitively, and this kind of historical Java library can have original POMs sometimes.

**Comment by fommil** [comment]
Re: LICENSE I'd need to include the license along with your jar if we're going to distribute it, but it's much easier if you just bundle the license in the jar.

I'll need a few days sorry, got a lot on at the moment and just need to find a moment.

**Comment by fommil** [comment]
(I'd have a hell of a lot more free time if I could close down https://github.com/ensime/ensime-sbt/pull/122 which is impacting me in a very serious way at work)

**Comment by alexarchambault** [comment]
@fommil np, good luck with that! I should be able to manage to do this check myself... (Although I won't run ensime on the computed classpath after.)

**Comment by fommil** [comment]
booo!

**Comment by alexarchambault** [comment]
Ok, I'll give ensime another try :-) (in evil mode or from atom...)

**Comment by alexarchambault** [comment]
@fommil You pinged me recently about that on Gitter. What are you thoughts / plans about it? I was thinking about sending a PR, with the current launcher say, to ensime-vim (which is the ensime client I ended up using).

Are you fine with the current launcher (the 8 kB one, downloading its dependencies on first launch)? Or do you think a proguarded standalone one would be better?

**Comment by fommil** [comment]
A proguarded one would be ideal, I've been meaning the look into this but I have been working on a couple of critical issues that are distracting me from the things I want to be working on :-(

**Comment by alexarchambault** [comment]
I've been trying to generate a proguarded launcher, without success so far (although I'm sure I managed to have it work some time ago...). See the [topic/proguard](https://github.com/alexarchambault/coursier/tree/topic/proguard) branch, in particular its [`project/generate-proguarded-launcher.sh`](https://github.com/alexarchambault/coursier/blob/topic/proguard/project/generate-proguarded-launcher.sh) script.

For me, running `java -cp coursier-proguard.jar coursier.cli.Coursier` after having launched the script gives something like
```
Exception in thread "main" java.lang.VerifyError: Inconsistent stackmap frames at branch target 132
Exception Details:
  Location:
    coursier/Cache$.validateChecksum$67367a85(Lcoursier/core/Artifact;Ljava/lang/String;Lscala/collection/GenSeq;Ljava/util/concurrent/ExecutorService;)Lscalaz/EitherT; @132: new
  Reason:
    Type uninitialized 32 (current frame, stack[0]) is not assignable to 'scalaz/EitherT' (stack map, stack[0])
  Current Frame:
    bci: @97
    flags: { }
    locals: { top, 'coursier/core/Artifact', 'java/lang/String', 'scala/Option' }
    stack: { uninitialized 32, uninitialized 32, integer }
  Stackmap Frame:
    bci: @132
    flags: { }
    locals: { top, top, top, 'scala/Option' }
    stack: { 'scalaz/EitherT', 'scalaz/EitherT' }
  Bytecode:
    0x0000000: 1904 3a04 2a2b 2db7 0092 b600 b512 16bb
    0x0000010: 0021 592b b700 96b9 0117 0300 c000 3b4c
    0x0000020: bb00 7059 2bb6 00af 2cb9 0116 0200 594e
    0x0000030: c100 5899 0027 2dc0 0058 594e b600 eec0
    0x0000040: 0046 4eb2 0089 57bb 0035 592c 2b2d b700
    0x0000050: aa19 04b8 0105 4ca7 0028 b200 812d b600
    0x0000060: d599 0023 b200 8957 bb00 6f59 bb00 3759
    0x0000070: 2c2b b600 b6b7 00ab b701 00b8 0106 4c2b
    0x0000080: b701 01b0 bb00 5359 2db7 00e3 bf
  Stackmap Table:
    full_frame(@90,{Top,Object[#59],Object[#70],Object[#85]},{Uninitialized[#32],Uninitialized[#32]})
    full_frame(@127,{Top,Object[#115]},{Uninitialized[#32],Uninitialized[#32]})
    full_frame(@132,{Top,Top,Top,Object[#85]},{Object[#112],Object[#112]})

	at coursier.cli.CacheOptions$.apply$default$1(Coursier.scala:53)
	at coursier.cli.Coursier$fresh$macro$1789$1.inst$macro$1768$lzycompute(Coursier.scala:508)
	at coursier.cli.Coursier$fresh$macro$1789$1.inst$macro$1768(Coursier.scala:508)
	at coursier.cli.Coursier$fresh$macro$1789$1$$anonfun$inst$macro$1767$1.apply(Coursier.scala:1508)
	at shapeless.Lazy.value$lzycompute(lazy.scala:2034)
	at shapeless.Lazy.value(lazy.scala:1034)
	at caseapp.core.HListParser$$anonfun$hconsRecursive$1$$anon$4.<init>(HListParser.scala:115)
	at caseapp.core.HListParser$$anonfun$hconsRecursive$1.apply(HListParser.scala:1114)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.HListParser$$anonfun$hconsDefault$1.apply(HListParser.scala:1054)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.HListParser$$anonfun$hconsDefault$1.apply(HListParser.scala:1054)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.HListParser$$anonfun$hconsDefault$1.apply(HListParser.scala:1054)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.HListParser$$anonfun$hconsDefault$1.apply(HListParser.scala:1054)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.HListParser$$anonfun$hconsDefault$1.apply(HListParser.scala:1054)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.HListParser$$anonfun$hconsDefault$1.apply(HListParser.scala:1054)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.HListParser$$anonfun$hconsDefault$1.apply(HListParser.scala:1054)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.HListParser$$anonfun$hconsDefault$1.apply(HListParser.scala:1054)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.HListParser$$anonfun$hconsDefault$1.apply(HListParser.scala:1054)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.HListParser$$anonfun$hconsDefault$1.apply(HListParser.scala:1054)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.Parser$.generic$266b235d$186e08a3(Parser.scala:82)
	at coursier.cli.Coursier$fresh$macro$1789$1.inst$macro$1612$lzycompute(Coursier.scala:508)
	at coursier.cli.Coursier$fresh$macro$1789$1.inst$macro$1612(Coursier.scala:508)
	at coursier.cli.Coursier$fresh$macro$1789$1$$anonfun$inst$macro$1611$1.apply(Coursier.scala:1508)
	at shapeless.Lazy.value$lzycompute(lazy.scala:2034)
	at shapeless.Lazy.value(lazy.scala:1034)
	at caseapp.core.HListParser$$anonfun$hconsRecursive$1$$anon$4.<init>(HListParser.scala:115)
	at caseapp.core.HListParser$$anonfun$hconsRecursive$1.apply(HListParser.scala:1114)
	at caseapp.core.HListParser.apply(HListParser.scala:1023)
	at caseapp.core.Parser$.generic$266b235d$186e08a3(Parser.scala:82)
	at coursier.cli.Coursier$fresh$macro$1789$1.inst$macro$1604$lzycompute(Coursier.scala:508)
	at coursier.cli.Coursier$fresh$macro$1789$1.inst$macro$1604(Coursier.scala:508)
	at coursier.cli.Coursier$fresh$macro$1789$1$$anonfun$inst$macro$911$4.apply(Coursier.scala:1508)
	at shapeless.Lazy.value$lzycompute(lazy.scala:2034)
	at shapeless.Lazy.value(lazy.scala:1034)
	at caseapp.core.CommandsMessages$.ccons(Messages.scala:139)
	at coursier.cli.Coursier$fresh$macro$1789$1.inst$macro$911$lzycompute(Coursier.scala:508)
	at coursier.cli.Coursier$fresh$macro$1789$1.inst$macro$911(Coursier.scala:508)
	at coursier.cli.Coursier$.<init>(Coursier.scala:508)
	at coursier.cli.Coursier$.<clinit>(Coursier.scala:508)
	at coursier.cli.Coursier.main(Coursier.scala)
```

**Comment by fommil** [comment]
hmm, I wonder if maybe you can turn off some of the more aggressive bytecode optimisations and just have it exclude unused classes... then maybe runtime reflection could be getting in the way.

**Comment by alexarchambault** [comment]
@fommil Finally got it working. It requires passing the `-noverify` option to `java` though. None of the `-dont...` options of proguard seem to fix that. The launcher itself weights approx. 1.6 MB.

**Comment by fommil** [comment]
@alexarchambault great! We can talk about this and maybe hack it into ENSIME at ScalaSphere :smile:

BTW, for ENSIME purposes you do not need to bundle `scala-library`, `scala-reflect`, `scala-compiler` or `scalap` because we already have access to the user's installed jars. How big is the proguarded jar if you do that?

**Comment by alexarchambault** [comment]
It only depends on `scala-library` among those. Down to 1.3 MB without it.

**Comment by fommil** [comment]
is that all scalaz? Any feeling if using cats (or neither) would get that smaller?

**Comment by alexarchambault** [comment]
A `du -hs` on the directories of the proguarded JAR with no obfuscation gives:
```
7,1M	./coursier
2,0M	./scalaz
848K	./caseapp
232K	./scala
216K	./shapeless
 44K	./META-INF
 40K	./ch
 12K	./ammonite
```

Then looking into the `coursier` namespace:
```
3,6M	coursier/cli
1,2M	coursier/core
1,1M	coursier/maven
532K	coursier/ivy
148K	coursier/util
```

The `coursier.cli` namespace itself contains 777 `.class` files. For just a bunch of stub! The problem may lie in the type-level calculations of case-app, the lib it uses to parse command-line args. It uses a lot `shapeless.Lazy`, which itself leads to a lot of intermediate classes. I'll try to switch to `Strict` from shapeless 2.3.0-SNAPSHOT, that was added precisely to prevent generating lots of these.

**Comment by fommil** [comment]
:smile: yeah, we're ok with snapshot stuff because this is an app, not a library

**Comment by alexarchambault** [comment]
~120 kB less with `Strict`, so down to 1.1~1.2 MB... @fommil  What would be the ideal size for you?

**Comment by fommil** [comment]
honestly, a lot smaller than that :disappointed: we are hoping to ship the jar with all the clients, which means that users would download it everytime they update their client. We could hack it by having an optional dependency in emacs, but I don't know if the other clients could do the same.

Or... maybe we could bootstrap downloading one jar. In which case maybe 1MB is not so bad. But I don't think Emacs is particularly good at downloading binary files.

**Comment by hedefalk** [comment]
@fommil Uuh, I just spawn a curl… Probably will break on Windows…
